require 'helper'

context 'Consumer' do
  setup do
    setup_db
    @session  = QueueClassic::Session.new( database_url )
    @consumer = @session.consumer_for( 'foo' )
    @producer = @session.producer_for( 'foo' )
  end

  teardown do
    teardown_db
  end

  test "consumers have a unique identifier generated by the database" do
    assert_match /consumer-(\d+)/, @consumer.consumer_id
  end

  test 'consumer can reserve an item on the queue' do
    assert_equal 0, @producer.queue.size
    @producer.put( "a message")
    assert_equal 1, @consumer.queue.size
    assert_equal 0, @consumer.queue.reserved_size
    assert_equal 1, @consumer.queue.ready_size

    item = @consumer.reserve
    assert_equal 0, @consumer.queue.ready_size
    assert_equal 1, @consumer.queue.reserved_size

  end
  test 'producer can add an item to the queue' do
    p = @session.producer_for('foo')
    assert_equal 0, p.queue.size
    p.put( "a message")
    assert_equal 1, p.queue.size
  end
end
