require 'helper'

context 'Producer' do
  setup do
    setup_db
    @session = QueueClassic::Session.new( database_url )
    @producer = @session.producer_for( 'foo' )
  end

  teardown do
    @session.close
    teardown_db
  end

  test "producers have a unique identifier generated by the database" do
    assert_match /producer-foo-(\d+)/, @producer.producer_id
  end

  test 'producer can add an item to the queue' do
    assert_equal 0, @producer.queue.processing_count
    @producer.put( "a message")
    assert_equal 1, @producer.queue.processing_count
  end

  test 'a producer produces a message in the ready state' do
    msg = @producer.put( "a message")
    assert_equal :ready, msg.state
    assert msg.ready?
  end

end
